apiVersion: v1
kind: Service
metadata:
  name: {{ include "blacklister.fullname" . }}
  labels:
    app.kubernetes.io/component: network
    {{- include "blacklister.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blacklister.selectorLabels" . | nindent 4 }}
